feat: Creates tests.
fix: Refactors project's structure to include central solution and reference tests properly.

feat: Creates src project with BaseDDD.Cli.

feat: Creates Verifiers and Helpers to prevent Commands from accessing Infrastructure and Templates from ever interacting with System.IO.

test: Creates Architecture, Integration and Unit tests.

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -4,4 +4,11 @@ echo "Running BaseDDD pre-push..."
 
 dotnet format --verify-no-changes || exit 1
 dotnet build -c Release || exit 1
-dotnet test || exit 1
+dotnet test \
+  --configuration Release \
+  --collect:"XPlat Code Coverage"
+
+if [ $? -ne 0 ]; then
+  echo "Tests failed"
+  exit 1
+fi
